/**:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    exposure_time: 3500
    gain: 15.0
    camera_name: "hikvision"
    use_sensor_data_qos: true
    frame_rate: 30
    recording: false
